<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <RuntimeFrameworkVersion>7.0.0</RuntimeFrameworkVersion>
    <RollForward>LatestMinor</RollForward>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UserSecretsId>07045989-41b7-4245-89ae-ff1be61c7e4c</UserSecretsId>
    <Version>$(VersionPrefix)1.2.0.1</Version>
    <ApplicationIcon>Resources\EdgeAlertIcon2.ico</ApplicationIcon>
    <Configurations>Debug;Release;EdgeAlertSignalClient2;EdgeAlertSignalClient1</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\alert.mp3" />
    <None Remove="Resources\edgealert.json" />
    <None Remove="Resources\EdgeAlert.png" />
    <None Remove="Resources\edgealert2.json" />
    <None Remove="Resources\EdgeAlertIcon.ico" />
    <None Remove="Resources\edgealert_splash.png" />
    <None Remove="Resources\Edgebits.ico" />
    <None Remove="Resources\Edgebits2.ico" />
    <None Remove="Resources\edgebits_icon.png" />
    <None Remove="Resources\edgebits_splash_2023.png" />
    <None Remove="Resources\green_icon.png" />
    <None Remove="Resources\green_icon_small.png" />
    <None Remove="Resources\Minimise.png" />
    <None Remove="Resources\red_icon.png" />
    <None Remove="Resources\red_icon_small.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\edgealert.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\edgealert2.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EdgeAlertIcon2.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.8.2" />
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.1" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="IPAddressRange" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeAlertDomain\EdgeAlertDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\alert.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EdgeAlert.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EdgeAlertIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\edgealert_splash.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Resources\Edgebits.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Edgebits2.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\edgebits_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\green_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\green_icon_small.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Minimise.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\red_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\red_icon_small.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\EdgeAlertIcon2.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Release\net7.0-windows\Resources\" />
  </ItemGroup>

</Project>
